sudo: false
language: node_js
node_js:
- '6'
- '5'
- '0.12'
script: npm run build
branches:
  only:
  - master
deploy:
  provider: npm
  on:
    branch: master
  api_key:
    secure: v4EdSKli2zyL1f4WxhPiOUUmXQ778+cTBdkdEAO4f/SVqZtsyW7U9HlKPm8Wl74Fjfv1oCVceLpkzS38rQJL7njqk+mgWNUU7aU5sl+5NSKYMkiVSojccz5szUlTWRQFzmvfMSKdkyLONEsrWhIYufqrZ5ybgKbU74c8dfwVnPWyvYGmhJ94GBsHy3EbFuvnh3KY5Uf2fMdc6UFq4jhOuINOQSx1ZvHwZVf5LpFRnTW7bN7cSePQmMiF2/JDsYi0P9DkbecnlWKkjW8LVl4ZJ1/kwnloshQQmNXYDQ5pg01ahSULyBvQJXvSCML5YragC7cX7SuAjqbu+bD6dCLmeFZP0SyqO3qTaGdWpAJYLUajTXTEGvIbHAKbEOYBhrUDi1gMoTv6kcGFuezzAeMp4SWuBwG6ZHVKNRDFJdrlrXMsJbLSXPz0o0OROBNeU49eQssiZGIDuivHfy7HDNDzUGRwBANCReqMRf3yThZYxzqEl2fyYQBuQUwu44gTj1LyGN5HFo7cB/WoEHrXdUl4XrfM4qYgt2fmX1vb2+pJ7ytMhHgEVplo2+wEePjouRIa9GBgc0lNpeYaBht+3kEyoz863066cc/xDRC6mKM9Sl1i2pkWTOgYfxX9K0tKLVdKNZm1gFciRT7VWTjSp1g15CPIO8QzYisOST/H+vuBzBM=
